export interface ZapatillaDescripcion {
    id:number,
    nombre:string,
    precio:number,
    color:string,
    ano:number,
    marca:string,
    linkcompra:string,
    imagen1:string, 
    imagen2:string, 
    imagen3:string,
    imagen4:string,
    disciplina:string,
    material:string,
    descripcionProducto:string,
}
